melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 32000
  clamp: 0.00001
  scale_factor: 4

data_folder: data/
valid_set_size: 15
valid_set_preferred_folders:
  - test
ignored_phonemes:
  - AP
  - SP
  - <AP>
  - <SP>
  - ''
  - pau
  - cl
data_augmentation:
  size: 2 # If the data contains unlabeled data, it must be equal to or greater than 1.
  key_shift_choices: [ 1, 2, 3, 4, 5, 6,-1,-2,-3,-4,-5,-6 ]

max_length: 45 # unit: second
