mq:
  END_POINT : "https://oss-cn-zhangjiakou.aliyuncs.com"  # OSS 外网节点
  ACCESS_KEY_ID : "YOUR_ACCESS_KEY_ID"
  ACCESS_KEY_SECRET : "YOUR_ACCESS_KEY_SECRET"
  BUCKET_NAME : "samoye-exp-source"  # 你的 bucket 名称

  MQCP_HOST : 'rabbitmq-serverless-cn-jeo3og3a00f.cn-zhangjiakou.amqp-2.net.mq.amqp.aliyuncs.com'
  MQCP_PORT : 5672
  MQCP_VHOST : 'samoye-exp'
  MQCP_USER : 'YOUR_MQCP_USER'
  MQCP_PASS : 'YOUR_MQCP_PASS'
  
  # Queue Names to your service
  SUBQ_NAME : 'create_music_03_soundtrack_process'
  PUBQ_NAME : 'create_music_03_soundtrack_process_resp'

oss:
  host : "https://samoye-exp-source.oss-cn-zhangjiakou.aliyuncs.com"

processor:
  device_list : [0,1,2,3]
  use_denoise : True
  uvr_path : '/app/data/UVR5_Linux/models/VR_Models/9_HP2-UVR.pth'

  model : "uvr" #uvr/demucs
