mq:
  END_POINT : "https://oss-cn-zhangjiakou.aliyuncs.com"  # OSS 外网节点
  ACCESS_KEY_ID : "LTAI5tKhVqkUUDmSYuQoBGiT"
  ACCESS_KEY_SECRET : "9L3YRpWX9AH31MnzeVOY2QSSfIy2eD"
  BUCKET_NAME : "caichong-source"  # 你的 bucket 名称
render:
  keepfile: False
  effector: "/configs/effector_configs/default.txt"
  volume_norm:
    vocal: -19.592071581854302
    acc: -25.7
    output: -16
  volume_db:
    vocal: 0
    acc: 0
